[package]
authors = ["Victor Koenders <victor.koenders@gmail.com>"]
name = "exceptional"
version = "0.1.0"

[dependencies]
chrono = "0.4.11"
serde = "1.0.114"
serde_json = "1.0.56"
serde_derive = "1.0.114"
