[package]
authors = ["Victor Koenders <victor.koenders@gmail.com>"]
name = "exceptional"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
serde = "1.0.116"
serde_json = "1.0.58"
serde_derive = "1.0.116"
